project:
  type: website
  output-dir: docs
  
website:
  title: "Will King"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/willking98/website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Will King"

format:
  html:
    theme: morph
    toc: true

editor: source

